# Generated by Django 2.0.2 on 2018-02-23 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='标题')),
                ('content', models.TextField(verbose_name='原始内容')),
                ('content_type', models.CharField(choices=[('md', 'markdown file'), ('rt', 'richtext file'), ('txt', 'plain text')], max_length=4, verbose_name='内容类型')),
                ('abstract', models.TextField(verbose_name='摘要')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='上次改动时间')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('voted_up', models.IntegerField(default=0, verbose_name='支持')),
                ('voted_down', models.IntegerField(default=0, verbose_name='反对')),
                ('viewed', models.IntegerField(default=0, verbose_name='浏览')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
