# Generated by Django 2.0.2 on 2018-02-26 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=14, verbose_name='兴趣组名称')),
                ('info', models.TextField(verbose_name='兴趣组说明')),
                ('thumbnail', models.FileField(upload_to='uploads/thumbnail/collections', verbose_name='缩略图')),
                ('admin', models.ManyToManyField(related_name='collections_in_charge', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('members', models.ManyToManyField(related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/image/articles')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='banner标题')),
                ('img', models.FileField(upload_to='uploads/image/slides', verbose_name='图片')),
                ('description', models.CharField(max_length=20, verbose_name='banner描述')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='_tags',
            field=models.TextField(default='none', verbose_name='标签'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='img_view',
            field=models.FileField(default='none', upload_to='uploads/thumbnail/article', verbose_name='缩略图'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('md', 'markdown file'), ('rt', 'richtext file')], max_length=4, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发表时间'),
        ),
        migrations.AddField(
            model_name='inarticleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Article'),
        ),
    ]
