# Generated by Django 2.0.2 on 2018-02-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180226_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='banner标题')),
                ('img', models.ImageField(upload_to='uploads/image/slides', verbose_name='图片')),
                ('description', models.CharField(max_length=20, verbose_name='banner描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='article',
            name='img_view',
            field=models.ImageField(upload_to='uploads/thumbnail/article', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(upload_to='uploads/thumbnail/collections', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='inarticleimage',
            name='image',
            field=models.ImageField(upload_to='uploads/image/article'),
        ),
    ]
